name: Containerize and/or deploy

concurrency:
  group: ${{ github.ref }}
  # only cancel running builds for branches other than master
  cancel-in-progress: ${{ github.ref_name != 'master' }}

on:
  workflow_dispatch:
    inputs:
      force-version:
        description: 'Force the image version to deploy (leave empty to infer from branch HEAD)'
        type: string
        required: false

jobs:
  containerize:
    runs-on: ubuntu-20.04
    outputs:
      tag: ${{ steps.docker.outputs.tag }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Docker image tag version
        id: docker
        run: |
          if [[ ! -z "${{ inputs.force-version }}" ]] ; then
            echo "tag=${{ inputs.force-version }}" | tee $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == refs/tags/* ]] ; then
            echo "tag=${{ github.ref_name }}" | tee $GITHUB_OUTPUT
          else
            echo "tag=${{ env.GITHUBX_SHA_SHORT }}" | tee $GITHUB_OUTPUT
          fi
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup Docker
        uses: docker/setup-buildx-action@v1
      - name: Setup Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: mrschyzo/instrument-search-listener:${{ steps.docker.outputs.tag }}
          tags: type=raw,value=${{ steps.docker.outputs.tag }}
      - name: Build Image
        run: docker build -t mrschyzo/instrument-search-listener:${{ steps.docker.outputs.tag }} .
      - name: Show Container
        run: docker images
      - name: Publish
        run: docker push mrschyzo/instrument-search-listener:${{ steps.docker.outputs.tag }}
      - name: Open me to see the docker image version
        run: echo "📦 Container version is ${{ steps.docker.outputs.tag }} 📦"
